### ISSUE TITLE
In the file App.cpp createCurlExecutor() is present

### ISSUE THREAD

**Issue by puneetugru** [oatpp/example-api-client#1]
Hi Leonid,

In the file App.cpp, createCurlExecutor() is present.
But when I try to use the same for my REST API Client, I'm getting below error,

src/App.cpp: In function ‘void run()’:
src/App.cpp:39:26: error: ‘createCurlExecutor’ was not declared in this scope
   auto requestExecutor = createCurlExecutor();
                          ^~~~~~~~~~~~~~~~~~
src/App.cpp:39:26: note: suggested alternative: ‘requestExecutor’
   auto requestExecutor = createCurlExecutor();
                          ^~~~~~~~~~~~~~~~~~
                          requestExecutor

Is createCurlExecutor deprecated?

**Comment by lganzzzo** [comment]
Hello @puneetugru ,

The `CurlExecutor` here is added for demo purposes to show that one can substitute different executors to be used with Api Client.

However It is recommended to use oatpp-native `oatpp::web::client::HttpRequestExecutor` executor for ApiClient.

Best Regards,
Leonid
