### ISSUE TITLE
Reg: Using Executor from Server ?

### ISSUE THREAD

**Issue by bkannadassan** [oatpp/example-api-client#2]
Hi Leonid,

   From server I need to get the executor so that I can use in client as well..

```cpp
  OATPP_CREATE_COMPONENT(std::shared_ptr<oatpp::network::server::ConnectionHandler>, serverConnectionHandler)([] {
    OATPP_COMPONENT(std::shared_ptr<oatpp::web::server::HttpRouter>, router); // get Router component
    OATPP_COMPONENT(std::shared_ptr<oatpp::async::Executor>, executor); // get Async executor component
    return oatpp::web::server::AsyncHttpConnectionHandler::createShared(router, executor);
  }());
```
I am planning to add a global variable and capture this in controller, do you have any better suggestion on the same ?. Since I feel my approach looks like a hack.

rgds
Balaji Kamal Kannadassan

**Comment by lganzzzo** [comment]
Hey @bkannadassan ,

If you already created executor component, then it is available in the system and you may inject it anywhere you want.

#### Create Executor component

```cpp
  OATPP_CREATE_COMPONENT(std::shared_ptr<oatpp::async::Executor>, executor)([] {
    return std::make_shared<oatpp::async::Executor>(1, 1, 1);
  }());
```

#### Inject it in Controller

```cpp
class MyController : public ... {
private:
  OATPP_COMPONENT(std::shared_ptr<oatpp::async::Executor>, executor);

};
```

---

> From server I need to get the executor so that I can use in client as well..

You don't need to explicitly specify executor for Client. 
Client will execute async requests in the same coroutine-call-stack. Thus client request will be executed by the same executor as the caller coroutine.

```cpp

  /* Use client to access remote resource in async manner.  */
  /* Client coroutine is executed in the same Executor as the server coroutine which serves the endpoint */
  ENDPOINT_ASYNC("GET", "/api/get", TestApiGet) {
    
    ENDPOINT_ASYNC_INIT(TestApiGet)
    
    Action act() override {
      /* Get remote resource in async manner  */
      return controller->myApiClient->apiGetAsync().callbackTo(&TestApiGet::onResponse);
    }
    
    Action onResponse(const std::shared_ptr<IncomingResponse>& response){
      /* We have response. Now we have to read the body in async-way */
      return response->readBodyToStringAsync().callbackTo(&TestApiGet::returnResult);
    }
    
    Action returnResult(const oatpp::String& body) {
      /* Now we have the body too!!! */
      return _return(controller->createResponse(Status::CODE_200, body));
    }
    
  };
```

Example is taken from [example-libressl](https://github.com/oatpp/example-libressl/blob/master/src/controller/MyController.hpp#L110)

Best Regards,
Leonid

**Comment by bkannadassan** [comment]
Hi Leonid,

    I need to have a separate client and server component. Hence I have gone with the same implementation of the example for client and server of yours.

` executor = components.executor.getObject();`

Hence with above I am getting executor and using below..

`executor->execute<GETServiceInfoCoroutine>(client, "consul", 456);`

Now when we receive a response we receive a list of services from consul, When tried reading to Dto

`response->readBodyToDtoAsync<oatpp::consul::rest::ConsulServiceMetadata>`

I noticed that I need objectMapper and looks like the same is a protected element m_objectMapper.

```
class ClientCoroutine_postBodyAsync : public oatpp::async::Coroutine<ClientCoroutine_postBodyAsync> {
public:
  static std::atomic<v_int32> SUCCESS_COUNTER;
private:
  OATPP_COMPONENT(std::shared_ptr<app::Client>, appClient);
  OATPP_COMPONENT(std::shared_ptr<oatpp::data::mapping::ObjectMapper>, objectMapper);
public:
```

I saw above code and tried adding objectMapper to my co-routine and I got compilation error..

```
In file included from /root/core/dhng/infra/unimain/oatpp/src/RMClient.cpp:5:0:
/root/core/dhng/infra/unimain/oatpp/src/RMClient.hpp:46:74: error: ‘objectMapper’ is not a type
     OATPP_COMPONENT(std::shared_ptr<oatpp::data::mapping::ObjectMapper>, objectMapper);
                                                                          ^
/root/core/dhng/infra/unimain/oatpp/src/RMClient.hpp:46:86: error: ISO C++ forbids declaration of ‘OATPP_COMPONENT’ with no type [-fpermissive]
     OATPP_COMPONENT(std::shared_ptr<oatpp::data::mapping::ObjectMapper>, objectMapper);
                                                                                      ^
make[2]: *** [../infra/unimain/oatpp/CMakeFiles/oatpp-api-client-lib.dir/src/RMClient.cpp.o] Error 1
make[1]: *** [../infra/unimain/oatpp/CMakeFiles/oatpp-api-client-lib.dir/all] Error 2
```

Please let me know if I am missing something..

rgds
Balaji Kamal Kannadassan

**Comment by bkannadassan** [comment]
Hi Leonid,

    I figured it out, looks like I have to include header AppComponent.hpp before I can use this. 
Once I included the same now its working fine..

rgds
Balaji Kamal Kannadassan

**Comment by lganzzzo** [comment]
Hello @bkannadassan ,

Yes you may inject ObjectMapper in the coroutine. Also if you have previously injected/passed object mapper to the Controllers' constructor you may just call `controller->getDefaultObjectMapper`

Regards,
Leonid
