### ISSUE TITLE
 support https?

### ISSUE THREAD

**Issue by xingyun86** [oatpp/example-api-client#3]
If I couldn't use curl, support https?

**Comment by xingyun86** [comment]
> If I couldn't use curl, support https?

I found a problem. Any way I use curl or not, but the demo return 301 like this:
============================================
```
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by lganzzzo** [comment]
Hey @xingyun86 ,

301 means that the endpoint was moved. Look at the location header to find the new endpoint address.

Regards,
Leonid

**Comment by xingyun86** [comment]
> Hey @xingyun86 ,
> 
> 301 means that the endpoint was moved. Look at the location header to find the new endpoint address.
> 
> Regards,
> Leonid

Ok.Thanks very much!
