### ISSUE TITLE
Windows mingw compile error

### ISSUE THREAD

**Issue by mohammad-nazari** [oatpp/example-api-client#5]
ConnectionProvider.cpp:300:5: error: 'inet_ntop' was not declared in this scope inet_ntop(AF_INET, &sockAddress->sin_addr, strIp, INET_ADDRSTRLEN);
Windows, MinGW64, g++, cmake, clion

**Comment by lganzzzo** [comment]
Closing this as a duplicate of https://github.com/oatpp/oatpp/issues/324
